In [44]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [45]:
data_2022= pd.read_csv('C:/Users/sivar/capstoneB/data/processed_22.csv')
data_2023 = pd.read_csv('C:/Users/sivar/capstoneB/data/processed_23.csv')
data_2024 = pd.read_csv('C:/Users/sivar/capstoneB/data/processed_24.csv')
data_2025 = pd.read_csv('C:/Users/sivar/capstoneB/data/processed_25.csv')

In [46]:
data_2022.head(25)
# change date to months for summer months and winter

,date,roiCount,ml_analyzed,ROI_per_ml,Lpoly_expected,Lpoly_expected_ml,Pmicans_expected,Pmicans_expected_ml,Area,B180,...,HOG79,HOG80,HOG81,Area_over_PerimeterSquared,Area_over_Perimeter,H90_over_Hflip,H90_over_H180,Hflip_over_H180,summedConvexPerimeter_over_Perimeter,rotated_BoundingBox_solidity
0,20221005,213.288889,4.893459,43.686985,22.935411,4.709407,13.751131,2.812309,11974.557229,0.928882,...,0.611308,0.095367,0.274156,0.041771,22.170160,1.266836,1.313910,1.068659,0.791211,0.631238
1,20221006,162.452830,4.894287,33.366936,13.319224,2.763376,12.074286,2.503794,11823.709733,0.934288,...,0.611941,0.096601,0.273971,0.045117,22.886624,1.297578,1.357131,1.074133,0.813061,0.646811
2,20221007,169.980000,4.872823,34.833416,5.074974,1.040254,43.708223,8.964823,10610.368513,0.935896,...,0.620756,0.098899,0.275299,0.046589,21.911387,1.437337,1.431526,1.023397,0.827414,0.642660
3,20221008,336.345455,4.859085,69.553816,9.665164,2.021317,114.070859,23.494854,9582.249814,0.934213,...,0.630919,0.098680,0.271302,0.046811,20.918614,1.501327,1.517644,1.064838,0.834406,0.635710
4,20221009,561.684211,4.786618,118.117103,47.861245,10.082290,67.474689,14.179606,10906.921467,0.930262,...,0.619425,0.094373,0.272369,0.043465,21.595006,1.312042,1.364307,1.068552,0.803011,0.634383
5,20221010,671.339286,4.764006,142.216029,26.403383,5.580180,62.548540,13.251899,11316.797985,0.929199,...,0.616166,0.094620,0.273897,0.042497,21.737208,1.272681,1.331744,1.072130,0.794485,0.632493
6,20221011,601.100000,4.787495,127.216492,18.992023,4.048607,60.832939,13.022101,11692.809870,0.928104,...,0.612701,0.091996,0.274808,0.042491,22.030671,1.307359,1.339051,1.067091,0.791687,0.637955
7,20221013,489.500000,4.827143,101.419554,5.156239,1.068897,37.887665,7.849132,11907.924373,0.937290,...,0.617061,0.095793,0.266448,0.045938,23.221160,1.239748,1.386236,1.128195,0.818090,0.642967
8,20221014,1472.603774,4.500468,341.099674,1.056346,0.230012,130.325762,30.230991,9806.111486,0.932721,...,0.635595,0.111816,0.281004,0.049729,21.121535,1.765413,1.642962,0.972964,0.843396,0.660394
9,20221019,474.000000,4.839772,98.228363,0.025648,0.005313,37.602989,7.799686,6509.605504,0.925903,...,0.677491,0.149322,0.302014,0.058085,18.640867,2.623199,2.219075,0.892241,0.902179,0.695301
10,20221020,557.603448,4.798546,117.054306,0.583053,0.122917,36.317994,7.615980,10128.851195,0.924725,...,0.643329,0.124086,0.285423,0.049873,21.047071,2.318551,2.071161,0.981489,0.846325,0.665399
11,20221021,345.542857,4.869174,71.229382,1.478075,0.305259,9.889418,2.035039,11800.302016,0.918847,...,0.625952,0.111923,0.277815,0.044722,22.146528,1.771621,1.686833,1.042846,0.809853,0.643854
12,20221022,222.862069,4.896622,45.736892,0.690282,0.142291,5.408903,1.109217,8266.476978,0.922043,...,0.659420,0.126535,0.292030,0.048561,18.832134,2.235566,1.976588,0.937228,0.844598,0.661266
13,20221023,168.086207,4.898766,34.373832,0.687157,0.141148,5.431708,1.111609,8603.929712,0.914060,...,0.662559,0.117731,0.281900,0.047891,18.873426,1.881175,1.703752,0.961333,0.832502,0.648305
14,20221024,100.206897,4.876263,20.524392,0.300179,0.061724,3.686791,0.754350,7140.009336,0.922084,...,0.681083,0.130749,0.288718,0.053657,17.914908,2.394470,2.097501,0.959162,0.868725,0.676355
15,20221025,139.705882,4.873283,28.639359,1.045792,0.214416,4.900398,1.007757,9945.442735,0.935805,...,0.639658,0.114729,0.285459,0.049422,20.994451,1.683055,1.579184,0.996405,0.838528,0.674236
16,20221026,171.534483,4.894773,35.064402,1.868165,0.382443,6.796295,1.390907,11066.908214,0.930770,...,0.630017,0.105700,0.277291,0.046153,21.704295,1.495947,1.531564,1.077327,0.816901,0.658379
17,20221027,121.534483,4.883812,24.861705,1.238728,0.253011,3.719064,0.760919,10292.513572,0.925535,...,0.633363,0.114049,0.282329,0.046359,20.852392,1.657353,1.541855,1.016760,0.820192,0.650889
18,20221028,228.155172,4.885541,46.822689,4.851896,0.994650,10.648164,2.179591,12673.755204,0.932581,...,0.613901,0.100931,0.272127,0.043877,23.184463,1.401192,1.417841,1.074908,0.801522,0.647965
19,20221029,361.157895,4.853032,74.529524,8.781223,1.814350,13.238056,2.731377,11502.894005,0.929703,...,0.615996,0.098052,0.277048,0.042907,22.005615,1.291995,1.396888,1.113877,0.798554,0.636488
20,20221030,341.827586,4.861807,70.368679,11.826671,2.436358,9.751402,2.006736,11476.699992,0.926720,...,0.616605,0.098393,0.276973,0.042485,21.805522,1.291310,1.334302,1.058586,0.795543,0.630972
21,20221031,285.897959,4.874683,58.698589,9.536120,1.959072,10.708406,2.198802,11492.993508,0.927229,...,0.618293,0.097096,0.276135,0.042172,21.751696,1.254414,1.331634,1.092555,0.790791,0.632238
22,20221101,378.773585,4.857217,78.232097,5.100495,1.053850,6.447218,1.331459,11401.788415,0.927754,...,0.619936,0.096750,0.276953,0.041228,21.449396,1.312576,1.356931,1.058482,0.787543,0.623357
23,20221106,766.545455,4.740487,162.001584,42.324341,8.952905,23.427556,4.953848,11716.568032,0.921207,...,0.617180,0.089699,0.273958,0.036547,20.494620,1.241794,1.281092,1.055436,0.753312,0.604467
24,20221107,657.224138,4.773201,138.540393,23.799470,5.039055,17.251567,3.637201,12227.997322,0.929876,...,0.611709,0.095326,0.274515,0.042064,22.471495,1.243388,1.323961,1.091242,0.790684,0.632851

In [47]:
y_data_train = data_2022['Lpoly_expected_ml']
x_data_train = data_2022.drop(columns=["date", "Lpoly_expected", "Lpoly_expected_ml","Pmicans_expected","Pmicans_expected_ml"],axis=1)

In [48]:
model = ElasticNet(alpha = 0.1, l1_ratio = 0.5)

In [49]:
predictions = model.fit(x_data, y_data)
y_pred = model.predict(x_data)
mse = mean_squared_error(y_data, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 1.5570067126969414

c:\Users\sivar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.286e+01, tolerance: 2.509e-02
  model = cd_fast.enet_coordinate_descent(

In [50]:
y_pred

array([ 2.32860627e+00,  1.53879338e+00,  2.23729256e+00,  3.67484111e+00,
        5.05959575e+00,  5.55388105e+00,  4.43799741e+00,  3.34465111e+00,
        1.07664732e+00,  1.62510303e-01,  9.15203798e-01,  3.05024788e-01,
        5.29119054e-01, -6.57920222e-03, -3.31088027e-01, -5.34033407e-01,
        3.03434633e-02,  5.02312420e-01,  1.00944462e+00,  3.40445179e+00,
        3.31485398e+00,  2.39965909e+00,  2.98231648e+00,  6.85201008e+00,
        4.86377640e+00,  2.82473665e+00,  9.00915020e-01,  4.70276047e-01,
        3.68204341e+00,  2.91591342e+00,  1.89548632e+00,  1.54407098e+00,
        9.02427086e-01,  6.17042088e-01,  1.09936377e+00, -3.59314451e-01,
       -3.54077407e-01, -4.74082263e-01,  1.26900830e+00, -1.94191275e-01,
       -4.36316160e-02,  5.14425005e-02,  1.63325229e+00,  9.58450733e-01,
       -4.14693083e-01,  8.00912431e-01, -7.59262404e-01,  5.63819546e-01,
        1.28159661e+00])

In [51]:
elasticnet_coeff = model.coef_
feature_coeff_df = pd.DataFrame({'Feature': x_data.columns, 'Coefficient': elasticnet_coeff})
feature_coeff_df.drop(feature_coeff_df[feature_coeff_df['Coefficient'] == 0].index, inplace=True)
feature_coeff_df.head(20)

                      Feature   Coefficient
0                    roiCount  7.132275e-02
2                  ROI_per_ml -3.007618e-01
3                        Area -1.621497e-03
7                   Biovolume -9.309339e-06
8          BoundingBox_xwidth  1.677739e-01
9          BoundingBox_ywidth  1.275436e-01
10                 ConvexArea -5.221435e-04
11            ConvexPerimeter  1.059803e-02
19            MinorAxisLength  5.503539e-03
20                Orientation -3.272773e-02
21                  Perimeter -4.927507e-02
23        RWhalfpowerintegral  8.469906e-07
24        RepresentativeWidth -1.270136e-01
25  RotatedBoundingBox_xwidth  1.992675e-01
26  RotatedBoundingBox_ywidth -1.002023e-01
28                SurfaceArea  2.206747e-04
35          moment_invariant5  4.226892e-03
37          moment_invariant7  3.528325e-03
43                 summedArea -1.741911e-03
44            summedBiovolume -9.731491e-06

In [52]:
y_data.describe()

count    49.000000
mean      1.560472
std       2.286280
min       0.005313
25%       0.229782
50%       0.498683
75%       1.959072
max      10.082290
Name: Lpoly_expected_ml, dtype: float64

In [53]:
y_data_val.describe()

count    185.000000
mean       2.916031
std        5.859977
min        0.000216
25%        0.056835
50%        0.580106
75%        2.565429
max       37.742277
Name: Lpoly_expected_ml, dtype: float64

In [54]:
y_data_val_2023 = data_2023['Lpoly_expected_ml']
x_data_val_2023 = data_2023.drop(columns=["date", "Lpoly_expected", "Lpoly_expected_ml"],axis=1)
y_pred_2023 = model.predict(x_data_val_2023)
df_describe = pd.DataFrame(y_pred_2023)
df_describe.describe()

                0
count  185.000000
mean     2.600778
std     10.423688
min    -31.914442
25%      0.311566
50%      1.765361
75%      3.431208
max    106.502708

In [55]:
mse_2023 = mean_squared_error(y_data_val_2023, y_pred_2023)
mse_2023

132.01317278202364

In [56]:
y_data_val_2024 = data_2024['Lpoly_expected_ml']
x_data_val_2024 = data_2024.drop(columns=["date", "Lpoly_expected", "Lpoly_expected_ml"],axis=1)
y_pred_2024 = model.predict(x_data_val_2024)
pd.DataFrame(y_pred_2024)

            0
0    5.050019
1    5.083641
2   -0.789822
3    2.403191
4    6.034118
..        ...
279  3.783683
280  4.042326
281  2.395213
282  5.708366
283  5.387011

[284 rows x 1 columns]

In [59]:
mse_2024 = mean_squared_error(y_data_val_2024, y_pred_2024)
mse_2024

21396113.51978889

c:\Users\sivar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.762e+01, tolerance: 2.509e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\sivar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.582e+01, tolerance: 2.509e-02
  model = cd_fast.enet_coordinate_descent(

alpha=   1 | 2023 MSE:        37.02 | 2024 MSE:    565547.39
alpha=  10 | 2023 MSE:        35.74 | 2024 MSE:      1094.68
alpha=  50 | 2023 MSE:        36.07 | 2024 MSE:       427.51
alpha= 100 | 2023 MSE:        36.23 | 2024 MSE:       238.25

c:\Users\sivar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.404e+01, tolerance: 2.509e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\sivar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.368e+01, tolerance: 2.509e-02
  model = cd_fast.enet_coordinate_descent(

In [63]:
reguralized_coeff = model2.coef_
reguralized_feature_coeff_df = pd.DataFrame({'Feature': x_data_train.columns, 'Coefficient': reguralized_coeff})
reguralized_feature_coeff_df.drop(reguralized_feature_coeff_df[reguralized_feature_coeff_df['Coefficient'] == 0].index, inplace=True)
reguralized_feature_coeff_df.head(20)

                Feature   Coefficient
0              roiCount  1.851148e-03
3                  Area  8.627582e-04
7             Biovolume -1.686189e-05
23  RWhalfpowerintegral  1.910719e-07
28          SurfaceArea  2.815509e-04
44      summedBiovolume -1.911457e-05
50    summedSurfaceArea  2.430158e-04

In [ ]:
total["date"] = pd.to_datetime(total["date"])
y = total['Lpoly_expected_ml']
X = total.drop(columns=["date", "Lpoly_expected", "Lpoly_expected_ml","Pmicans_expected","Pmicans_expected_ml"])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=23)

In [ ]:
elanetmod = Pipeline([
    ('scaler', RobustScaler()),
    ('model',  ElasticNet(alpha=1, l1_ratio=0.5, max_iter=10000)),
    
])
elanetmod.fit(X_train, y_train)
y_pred = elanetmod.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R^2 Score: {r2:.2f}")

In [ ]:
model_name = elanetmod.named_steps['model']
model_name_coeff = model_name.coef_
feature_coeff_df = pd.DataFrame({'Feature': X_train.columns, 'Coefficient': abs(model_name_coeff)})
feature_coeff_df.drop(feature_coeff_df[feature_coeff_df['Coefficient'] == 0].index, inplace=True)
feature_coeff_df.head(20).sort_values(by='Coefficient', ascending=True)