In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [6]:
data_2023 = pd.read_csv('C:/Users/sivar/capstoneB/data/processed_23.csv')
data_2024 = pd.read_csv('C:/Users/sivar/capstoneB/data/processed_24.csv')
data_2025 = pd.read_csv('C:/Users/sivar/capstoneB/data/processed_25.csv')

In [7]:
data_2023

,date,roiCount,ml_analyzed,ROI_per_ml,Lpoly_expected,Lpoly_expected_ml,Area,B180,B90,Bflip,...,HOG79,HOG80,HOG81,Area_over_PerimeterSquared,Area_over_Perimeter,H90_over_Hflip,H90_over_H180,Hflip_over_H180,summedConvexPerimeter_over_Perimeter,rotated_BoundingBox_solidity
0,20230302,1449.400000,4.502400,321.917200,0.217226,0.048247,6854.496690,0.858403,0.707589,0.869340,...,0.720004,0.116686,0.290015,0.041884,13.473042,3.123807,2.597118,0.898822,0.821564,0.612432
1,20230303,1687.928571,4.415571,382.267301,0.307581,0.069658,5351.646538,0.861207,0.712264,0.865950,...,0.713550,0.116239,0.295713,0.044948,12.525549,3.082428,2.731759,0.960057,0.849655,0.619506
2,20230304,1362.814815,4.523185,301.295383,0.151569,0.033509,4118.529779,0.833325,0.658100,0.846726,...,0.743122,0.122141,0.290284,0.045829,10.780124,3.320475,2.852056,0.930060,0.871359,0.606824
3,20230321,469.800000,4.838900,97.088181,0.003494,0.000722,2327.383061,0.829494,0.533966,0.855102,...,0.818850,0.121766,0.276407,0.042215,7.325911,5.293255,4.087189,0.856286,0.902342,0.608786
4,20230322,621.293103,4.786155,129.810481,0.008520,0.001780,3016.514303,0.828954,0.534235,0.847626,...,0.800858,0.120768,0.273564,0.041008,8.863398,5.492804,4.181484,0.872927,0.893572,0.603433
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,20231224,360.666667,4.878212,73.934191,34.753145,7.124156,11285.302252,0.937309,0.920201,0.931121,...,0.613885,0.103900,0.274368,0.048186,23.146031,1.346480,1.446064,1.134309,0.836000,0.653502
181,20231225,375.140351,4.874088,76.966270,31.437400,6.449904,10932.698069,0.936030,0.920055,0.929206,...,0.617115,0.101796,0.274937,0.046404,22.349626,1.286282,1.409572,1.129649,0.825002,0.642440
182,20231226,396.000000,4.866857,81.366678,32.174119,6.610862,10435.618190,0.931510,0.915334,0.924881,...,0.622435,0.099190,0.275089,0.044469,21.364054,1.274990,1.382656,1.115698,0.811484,0.635313
183,20231227,366.703704,4.876815,75.193280,18.770380,3.848901,10284.736717,0.931857,0.916278,0.926807,...,0.612878,0.099553,0.276391,0.044844,21.282885,1.279787,1.362002,1.092495,0.814636,0.635479
184,20231228,266.981132,4.911585,54.357430,12.713641,2.588501,10539.936756,0.935557,0.919240,0.928847,...,0.621732,0.100708,0.275903,0.045870,21.814262,1.278725,1.396622,1.122813,0.821359,0.642083

In [8]:
y_data = data_2023['Lpoly_expected_ml']
x_data = data_2023.drop(columns=['Lpoly_expected_ml'],axis=1)

In [9]:
model = ElasticNet(alpha = 0.1, l1_ratio = 0.5)

In [13]:
predictions = model.fit(x_data, y_data)
y_pred = model.predict(x_data)
mse = mean_squared_error(y_data, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 0.005259357952354323

c:\Users\sivar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.621e+00, tolerance: 6.318e-01
  model = cd_fast.enet_coordinate_descent(

In [47]:
elasticnet_coeff = model.coef_
feature_coeff_df = pd.DataFrame({'Feature': x_data.columns, 'Coefficient': elasticnet_coeff})
feature_coeff_df.drop(feature_coeff_df[feature_coeff_df['Coefficient'] == 0].index, inplace=True)
feature_coeff_df

                  Feature   Coefficient
0                    date  6.857680e-05
1                roiCount  5.015915e-05
4          Lpoly_expected  2.085786e-01
5                    Area -5.339993e-05
9               Biovolume  1.397023e-07
12             ConvexArea -1.474485e-05
25    RWhalfpowerintegral -5.908453e-09
30            SurfaceArea  3.392838e-06
37      moment_invariant5 -3.121275e-08
45             summedArea  1.680934e-05
46        summedBiovolume -2.468308e-08
47       summedConvexArea  2.340858e-05
48  summedConvexPerimeter  2.725879e-04
52      summedSurfaceArea -2.513247e-06